name: Pushing to NETLIFY for Deployment.
on: 
  push:
    branches: ['master']
    paths-ignore:
      - ".github/**"
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Looking for Updates to Deploy.
      uses: actions/checkout@v1
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    